# Generated by Django 3.2.3 on 2021-06-09 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sneaks', '0002_auto_20210609_0820'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
