# Generated by Django 3.2.3 on 2021-06-13 08:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sneaks', '0004_auto_20210611_1439'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='email',
        ),
    ]
