# Generated by Django 3.2.3 on 2021-06-13 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sneaks', '0005_remove_customer_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='email',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
